#!/bin/bash

# A simple script to setup SSH for lab machines
# Run this on your local machine
# Download a copy using the "Raw" button on GitHub
# Or by entering these commands into your terminal (replace <username> by your username, e.g. ./ssh.sh kss22):
#   curl https://raw.githubusercontent.com/Gum-Joe/some-tools/master/ssh.sh -o ./ssh.sh
#   chmod +x ./ssh.sh
#   ./ssh.sh <username>

# Usage: ./ssh.sh <username>
# E.g. ./ssh.sh kss22

# By Kishan Sambhi (kss22) (kishansambhi@hotmail.co.uk)
# Created with the help of GitHub Copilot

# MIT License
#
# Copyright (c) Kishan Sambhi
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Constants
# These define where we're going to write various things
SSH_KEY_NAME="doclab"
SSH_KEY_SCHEME="ecdsa"
SSH_BITS="521"
SSH_KEY_BASEPATH="$HOME/.ssh/${SSH_KEY_NAME}_${SSH_KEY_SCHEME}"
SSH_PRIVATE_KEY="${SSH_KEY_BASEPATH}"
SSH_PUB_KEY="${SSH_KEY_BASEPATH}.pub"

# Randomise shell used in case this script becomes popular and we hit one machine
SHELL_NUMBER=$(( (RANDOM % 5) + 1 ))
SHELL_USED="shell$SHELL_NUMBER.doc.ic.ac.uk"

# A simple script to setup SSH for lab machines
# STEPS:
# 1. Create keys locally
# 2. Copy keys to shell
# 3. append to authorized_keys2
# 4. Copy private & pub key to shell server
# 5. Setup ~/.ssh/config
# 6. test
#
# USAGE: ./ssh.sh <username>
printhelp() {
  echo "Usage: ./ssh.sh <username>"
  echo "This script sets up SSH for Imperial DoC lab machines for <username>"
  echo "Example usage: ./ssh.sh kss22"
}

if [ -z "$1" ]
    then
      echo "Please remember to enter a username."
      echo
      printhelp
      exit 0
fi





if [ ! -d $HOME/.ssh ]; then
	echo "ERROR: No SSH dir present"
	echo "This script is not prepared to deal with such an environment"
	exit 1
fi

# Safe territory - a username is defined
USER=$1

if [ "$USER" = "<username>" ]; then
  echo "ERROR: Please replace <username> with your actual username (imperial shortcode)."
  echo "Example usage: ./ssh.sh kss22"
  exit 1
fi

echo "Starting Lab SSH Setup for user $USER..."
echo "========================================"
echo "PHASE 1: Local SSH Key Generation"
echo "========================================"
echo "
What's going to happen: 
  We are going to generate SSH keys locally, used to login to the lab machines 
"
echo "Generating SSH keys..."
echo "You will be prompted several times - read the prompts and follow them"
echo "Hit enter to use the default (usually written in () at the end of the prompt) - generally this is what you want to do"
echo
echo "You will also be prompted for a passphrase. This is optional, but recommended." # Personally I don't have this
ssh-keygen -t $SSH_KEY_SCHEME \
  -b $SSH_BITS \
  -C "$USER@doc.ic.ac.uk Generated by ssh.sh script" \
  -f $SSH_PRIVATE_KEY
echo "========================================"
echo "WHAT JUST HAPPENED:"
# Explanation to user of the SSH keys just created, and why they are needed
echo "  We just generated a public and private key pair. The public key is used to identify you to the server, and the private key is used to decrypt the public key."
echo "  The public key is stored on the server, and the private key is stored locally. The private key may be encrypted with a passphrase (if you chose one), which you will be prompted for when you login."
echo "  The public key is stored in ~/.ssh/id_rsa.pub, and the private key is stored in ~/.ssh/id_rsa"
echo "  When you login, rather than be prompting for your imperial password, SSH will use these keys automatically to login into the server."
echo "  You can view the public key by running cat ~/.ssh/id_rsa.pub"
echo "  NEVER SHARE YOUR PRIVATE KEY WITH ANYONE. \
    If you do, they can login to the server as you."
echo "========================================"

# Shouldn't get here!
if [ ! -f "$SSH_PUB_KEY" ]; then
  echo "Error: $SSH_PUB_KEY does not exist."
  exit 1
fi

if [ ! -f "$SSH_PRIVATE_KEY" ]; then
  echo "Error: $SSH_PRIVATE_KEY does not exist."
  exit 1
fi


# Copy keys
echo "========================================"
echo "PHASE 2: Copy SSH keys to shell & authorise accross machines"
echo "========================================"
echo "Using ssh-copy-id to copy keys to shell entry points for DoC servers..."
echo "If you see a message like 'Are you sure you want to continue connecting (yes/no/[fingerprint])?', enter 'yes'."
echo "Please enter your REGULAR IMPERIAL LOGIN PASSWORD when prompted the password for $USER@$SHELL_USED (this should be the last time you enter it for an SSH session, from then on use the passcode set for the SSH key if you set one)"
if command -v ssh-copy-id &> /dev/null
then
  # BEGIN: ed8c6549bwf9
    if ssh-copy-id -i $SSH_PRIVATE_KEY $USER@$SHELL_USED; then
      echo "SSH key copy succeeded!"
    else
      echo "SSH key copy failed. This means something went wrong with the script!"
      echo "Please report this to the script creator."
      exit 1
    fi
  # END: ed8c6549bwf9
else
  echo "ssh-copy-if NOT FOUND. Please install ssh-copy-id and try again."
  echo "Contact the script author so he can add code that works if ssh-copy-id not installed"
  exit 1
fi

# Test auth
echo "Testing SSH auth..."
echo
if ssh -i $SSH_PRIVATE_KEY $USER@$SHELL_USED "echo 'SSH Auth Successful!' > /dev/null"; then
  echo "SSH succeeded!"
else
  echo "SSH failed. This means something went wrong with the script!"
  echo "Please report this to the script creator."
  exit 1
fi
echo



# We now attempt to ssh into the shell machine, and copy the keys to the other machines via authorised_keys2
echo "Copying keys to shell machine for use accross DoC machines.."
# Use SCP to copy SSH_PRIVATE_KEY and SSH_PUB_KEY to SHELL_USED using these keys to login
scp -i $SSH_PRIVATE_KEY $SSH_PRIVATE_KEY $USER@$SHELL_USED:~/.ssh/

if [ $? -eq 0 ]; then
  echo "Private key copy done."
else
  echo "Failed to copy keys to shell machine. Exiting..."
  exit 1
fi

scp -i $SSH_PRIVATE_KEY $SSH_PUB_KEY $USER@$SHELL_USED:~/.ssh/

if [ $? -eq 0 ]; then
  echo "Public key copy done."
else
  echo "Failed to copy keys to shell machine. Exiting..."
  exit 1
fi

# We also need to set correct permission
echo "Setting approriate permissions for private keys..."
echo "Setting permission locally (Owner read, write; everyone else: no perms)..."
chmod 600 $SSH_PRIVATE_KEY
if [ $? -eq 0 ]; then
  echo "Local permission set done."
else
  echo "Failed to set permissions locally. Exiting..."
  exit 1
fi
echo "Setting permissions on shell machines (Owner read, write; everyone else: no perms)..." 
ssh -i $SSH_PRIVATE_KEY $USER@$SHELL_USED "chmod 600 ~/.ssh/$(basename $SSH_PRIVATE_KEY)"
if [ $? -eq 0 ]; then
  echo "Remote permission set done."
else
  echo "Failed to set permissions on shell machine for private key. Exiting..."
  exit 1
fi


# Next: Append on machine to authroized_keys2
echo "Appending keys to authorized_keys2 on shell machine..."
echo "This will allow you to login to other DoC machines without having to enter your password."
if ssh -i $SSH_PRIVATE_KEY $USER@$SHELL_USED "cat ~/.ssh/$(basename $SSH_PUB_KEY) >> ~/.ssh/authorized_keys2"; then
  echo "Key append done."
else
  echo "Failed to append keys to authorized_keys2 on shell machine. Exiting..."
  exit 1
fi

echo
echo "The necessary presetup is now done - we have created our SSH keys and placed them onto the machines."
echo "We can now SSH into the machines! However we still need to SSH into shell, then the lab to get to lab machine"
echo "Let's make that more convienient by setting up a config file so it's only one command to get to the lab machine."
echo "========================================"
echo "PHASE 3: Setup SSH config file"
echo "========================================"

# Func to pick a lab machine for VSCode to lock onto
choose_lab_machine() {
  echo "Picking a random lab machine to use for VSCode etc...."
  LAB_MACHINE=$(ssh -i $SSH_PRIVATE_KEY $USER@$SHELL_USED "/vol/linux/bin/freelabmachine")
  if [ $? -eq 0 ]; then
    echo "Picked $LAB_MACHINE"
  else
    echo "Failed to pick a lab machine. Exiting..."
    exit 1
  fi
  SELECTED_LAB_MACHINE=$LAB_MACHINE
}

# Pick lab machine
choose_lab_machine

# TEMPLATE
complete_config="
### GENERATED BY SSH.SH SCRIPT ###

# These allow us to easily SSH into the shell machines
Host shell1.doc.ic.ac.uk
  User $USER
  HostName shell1.doc.ic.ac.uk
  IdentityFile $SSH_PRIVATE_KEY

Host shell2.doc.ic.ac.uk
  User $USER
  HostName shell2.doc.ic.ac.uk
  IdentityFile $SSH_PRIVATE_KEY

Host shell3.doc.ic.ac.uk
	User $USER
	HostName shell3.doc.ic.ac.uk
	IdentityFile $SSH_PRIVATE_KEY

Host shell4.doc.ic.ac.uk
  User $USER
  HostName shell4.doc.ic.ac.uk
  IdentityFile $SSH_PRIVATE_KEY

Host shell5.doc.ic.ac.uk
  User $USER
  HostName shell5.doc.ic.ac.uk
  IdentityFile $SSH_PRIVATE_KEY

# Use this target to SSH into a lab machine with VSCode
# Fixes a specific machine to SSH into
Host vscodelab
	User $USER
	# Change the machine name below to select a different machine
  # randomly selected at time of script run.
	HostName $SELECTED_LAB_MACHINE
  # randomly selected at time of script run - uses this to get to the lab machine
	ProxyJump $SHELL_USED 
	IdentityFile ~/.ssh/$(basename $SSH_PRIVATE_KEY)

# This one selects a random lab machine to SSH into
# Unfortunately, in my testing it does not work with VSCode
# So the VSCode one has to be fixed to a specific machine
Host anylab
	User $USER
	HostName $SHELL_USED
  # Explanation of the below: 
	RemoteCommand ssh -i ~/.ssh/$(basename $SSH_PRIVATE_KEY) -o StrictHostKeyChecking=no \$(/vol/linux/bin/freelabmachine)
	RequestTTY yes
	IdentityFile $SSH_PRIVATE_KEY
### END GENERATED BY SSH.SH SCRIPT SECTION ###
"

echo "Writing SSH Config file..."
echo "$complete_config" >> $HOME/.ssh/config

echo "SSH SETUP COMPLETE!"

# Contributions to automate this are welcome
print_manual_vscode_setting() {
  echo
  echo -e "\033[1mIMPORTANT ADDENUM:\033[0m Getting VSCode Remote SSH to work."
  echo "Unfortunately we're not quite done yet: VSCode Remote SSH will not work properly until you make a small change to your VSCode settings."
  echo "I would make this change automatically, however modifying the settings in a bash script is really hard, and not guaranteed to work accross platforms, and might mess up the settings file if done improperly (contributions to make this automated are welcome)."
  echo "Follow these steps:"
  echo "  1. Open VSCode"
  echo '  2. Open settings (the GUI for settings): keyboard shortcut is "Command+," or "Ctrl+,"'
  echo -e "  3. Search for 'remote.SSH.useLocalServer'. Make sure this is \033[1mUNTICKED\033[0m"
  echo -e "  4. Search for 'remote.SSH.remotePlatform'. Add a new entry called \033[1m'vscodelab'\033[0m with the value \033[1m'linux'\033[0m"
  echo "  5. Your settings save automatically, and now lab machine SSH should work!"
  echo
  echo "========================================"
}

echo "========================================"
echo "Files generated:"
echo "  Your SSH private key is located at: $SSH_PRIVATE_KEY"
echo "  Your SSH public key is located at: $SSH_PUB_KEY"
echo "  Your SSH config file is located at: ~/.ssh/config"
echo "========================================"
echo
echo -e "\033[1mNOW READ THE BELOW:\033[0m"
echo "You can now SSH into the shell machines using the following commands:"
echo
echo -e "\033[1mTO ACCESS LAB MACHINES (the important bit):\033[0m"
echo "  ssh anylab"
echo "  IMPORTANT: This SSH target will NOT work with VSCode or most other SSH dependent tools"
echo 
echo -e "\033[1mVSCODE NOTE: TO ACCESS LAB MACHINES WITH THE \033[4mVSCODE\033[0m\033[1m REMOTE DEV EXTENSION, or in anything that's not a regular linux shell:\033[0m"
echo "(if you don't have this extension, look it up - it lets you use VSCode on your machine as if you are on a remote machine via SSH!)"
echo "Select vscodelab as the target machine when setting up VSCode remote dev"
echo "  ssh vscodelab"
echo
echo -e "\033[1mVSCODE NOTE 2:\033[0m Remote Dev SSH might not immediately work - please see the addenum printed after this section for how to get VSCode Remote Dev SSH to work properly with lab machines"
echo
echo "TO ACCESS LAB SHELLS (these are the shells, not the lab machines themselves! Never work out of these!):"
echo "  ssh shell1.doc.ic.ac.uk"
echo "  ssh shell2.doc.ic.ac.uk"
echo "  ssh shell3.doc.ic.ac.uk"
echo "  ssh shell4.doc.ic.ac.uk"
echo "  ssh shell5.doc.ic.ac.uk"
echo 
echo "NOTE: To get vscodelab to work, we had to pick a specific lab machine to SSH into."
echo "This is fixed (unlike anylab which will pick a random machine each time)"
echo "You can change it in ~/.ssh/config"
echo " Your randomly selected machine was: $SELECTED_LAB_MACHINE"
echo
echo "========================================"
print_manual_vscode_setting
echo "Done."